# Generated by Django 5.2.7 on 2025-10-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
