# Generated by Django 5.2.7 on 2025-10-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_groceryitem_quantity_groceryitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='price',
            new_name='default_price',
        ),
    ]
