# Generated by Django 5.2.7 on 2025-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_price_groceryitem_default_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='default_price',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
